
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          feed_list: "https://consulenteseoweb.blogspot.com/feeds/posts/default?alt=rss,https://consulenteseoweb.wordpress.com/feed/,https://consulenteseoweb.tumblr.com/rss,https://consulenteseoweb.weebly.com/1/feed,https://www.diigo.com/rss/user/consulenteseoweb?sort=updated,https://www.evernote.com/shard/s477/sh/e3eb746a-1cde-5ddf-dd8a-00fc8d0ac6da/a34d3ece66813b1dc47eb7b0e0d65c84,https://on.narro.co/consulente.seo.web,https://trello.com/b/0tHCByN4/2nd-tier,https://feeds.buzzsprout.com/1728569.rss,https://www.youtube.com/feeds/videos.xml?channel_id=UCGAeN83y3CiSuNzuYe6GsoQ"
